### ISSUE TITLE
use_user_media device constraints do not allow for specifying the facingMode of the camera

### ISSUE THREAD

**Issue by glademiller** [Synphonyte/leptos-use#172]
Currently you can only specify whether there is video or not and adding the facingMode to the constraints isn't possible which means you will always get a camera with video but may not have the one that you want. 

Based on https://stackoverflow.com/questions/52812091/getusermedia-selecting-rear-camera-on-mobile

I would propose exposing an interface that could be in addition to what is already provided that would allow you to pass a raw MediaStreamConstraints object from web_sys.

**Comment by maccesch** [comment]
References:

https://docs.rs/web-sys/latest/web_sys/struct.MediaTrackConstraints.html#method.facing_mode
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#syntax
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints

It actually shouldn't be a direct `web-sys` object because you cannot instantiate it on the server. The `web-sys` support here is not very ergonomic anyway. So we should recreate this in the form of a builder pattern.

I imagine the usage being sth like the following

```rust
// takes simple bool
UseUserMediaOptions::default()
    .video(true)

// but also
UseUserMediaOptions::default()
   .video(
        VideoTrackContraints::default() 
            // takes a value directly which is the same as `exact`
            .facing_mode(FacingMode::User)
            // or takes a constrain
            .aspect_ratio(ConstrainDouble::default().min(0.5).max(1.2))
    )
```
