### ISSUE TITLE
wasm-bindgen version conflict...

### ISSUE THREAD

**Issue by sobamemil** [Synphonyte/leptos-use#176]
Does it not work with the latest wasm-bindgen (0.2.95) ??

`cargo metadata` exited with an error:     Updating crates.io index
    error: failed to select a version for `wasm-bindgen`.
        ... required by package `leptos-use v0.13.5`
        ... which satisfies dependency `leptos-use = "^0.13.5"` of package `...`
    versions that meet the requirements `=0.2.93` are: 0.2.93

**Comment by maccesch** [comment]
Are you using `cargo-leptos`?

**Comment by sobamemil** [comment]
Yes.

**Comment by maccesch** [comment]
In this case you're stuck at version `0.2.93` for now. Do you absolutely need the latest version?

**Comment by duncanawoods** [comment]
I see there is a pull request, is something blocking it getting merged in?

https://github.com/leptos-rs/cargo-leptos/pull/372

My only problem is the version conflict but it makes me nervous because it affects everything in a workspace. web-sys and js-sys also need to be kept at the older version.

**Comment by maccesch** [comment]
This is an unfortunate reality at the moment with the whole web-sys ecosystem. It's still very unstable and has sometimes breaking changes even on patch version increases so it's necessary to pin the versions down.

It's not so bad though because this is "just" a binding for the actual browser JavaScript APIs which are what they are in any case.

I'll release an updated version as soon as cargo-leptos updates.

**Comment by Nutomic** [comment]
In my case the problem was fixed simply by deleting Cargo.lock and running cargo check again.

**Comment by jheuel** [comment]
Leptos unpinned `wasm-bindgen` and is using version 0.2.95 since `leptos-0.7.0-rc1`. See leptos-rs/leptos#3186.
