### ISSUE TITLE
Support setting headers with `use_event_source` hook

### ISSUE THREAD

**Issue by tqwewe** [Synphonyte/leptos-use#188]
The `use_event_source` hook is great, however in my case I need to send an `Authorization` header to the endpoint, but leptos use doesn't seem to support this.

The alternative is simply appending `?access_token={}` to the url, however every other endpoint in my app uses the `Authorization` header, so it would be nice to keep it consistent.

**Comment by maccesch** [comment]
Unfortunately this is a limitation of the browser API itself (See https://stackoverflow.com/questions/28176933/http-authorization-header-in-eventsource-server-sent-events). 

Sending the auth token in the url is not a good idea because it's not encrypted by SSL. 

Websockets have the same limitation actually but with them you can send the auth token to server after a connection has been established. So maybe this would be a good idea?

**Comment by tqwewe** [comment]
What an interesting limitation I definitely didn't expect to be limited by the browser API directly here.

Websocket could work well, also for the fact that I'm using fresh tokens, and wasn't quite sure how I'd handle the SSE endpoint when the token is refreshed. Thanks for the reply and suggestions, sounds like I'll go with that approach
